#!/usr/bin/env bash
# installs and configure nginx

# Updates the system first
sudo apt-get -y update

# Downloads and installs Nginx
sudo apt-get -y install nginx

# Allow Nginx collection
sudo ufw allow 'Nginx HTTP'

# Prints hell world on web page
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html

# starts Nginx
sudo service nginx start
