#!/usr/bin/env bash
# Install and Configure Nginx

# Update kernel
sudo apt-get -y update

# Install nginx, if not installed
sudo apt-get -y install nginx

# Allow Nginx collection
sudo ufw allow 'Nginx HTTP'

# Replace home page with hello world
echo "Hello World" | sudo tee /var/www/html/index

# redirect and update custom 404 page
sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default

# restart nginx server
sudo service nginx restart
