#!/usr/bin/env bash
# This scripts is intended  to install and confgure Nginx as follows:

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Add files and directories
sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
echo "Hello World" > /var/www/html/index.html
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

#  Configure server as follows:
# + Listen to port 80
# + Add Custom header
sudo printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart