#!/usr/bin/env bash
# Install and configure Nginx HAProxy 

# Configure HAproxy frontend and backend
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 527927-web-01 100.25.109.49:80 check
    server 527927-web-02 54.209.222.176:80 check
"

# Update server packages
apt-get -y update
apt-get -y upgrade

# Intergrate server ppa
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

# install proxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
