#!/usr/bin/env bash
# Pings provided address 5 times

# Check if an argument is provided
if [[ -z "$1" ]]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Ping the provided IP address 5 times
ping -c 5 "$1"

# Store the exit status of the ping command
PING_EXIT_STATUS=$?

# Check the exit status of ping to provide a conclusion
if [[ ! PING_EXIT_STATUS -eq 0 ]]; then
    echo "Host $1 may be down or unreachable."
fi
