#!/bin/bash

# Find the PID of the process named "4-to_infinity_and_beyond"
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the PID is found
if [ -n "$pid" ];
then
    kill "$pid"
else
    exit
fi