#!/usr/bin/env bash
# Function to handle SIGTERM signal
sigterm_handler() {
    echo "I am invincible!!!"
    exit
}

# Trap SIGTERM signal and call sigterm_handler function
trap 'sigterm_handler' SIGTERM

# Loop indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
done