#!/usr/bin/env bash
# script that displays all active IPv4 IPs on the machine it’s executed on.

# Get all IPv4 addresses associated with active network interfaces
ipv4s=$(ifconfig | awk '/inet (addr:)?([0-9]*\.){3}[0-9]*/ {print substr($2, 6)}')

# Display the ips
echo "$ipv4s"