#!/usr/bin/env bash
# This runs apache on a designated docker container

# Making changes to conf file
# This addresses the issues affecting the apache server
echo 'ServerName localhost' >> /etc/apache2.conf

# Restarting apache
# This ensures the changes take effect
service apache2 start
