#!/usr/bin/env bash
# Configures a web servers to run Nginx as the nginx user

# replaces www-data with nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# replaces any occurence of 80 with 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# changes permissions for configuration files
chmod 644 /etc/nginx/nginx.conf

# kills the apache2 process
pkill apache2

# starts nginx
sudo -u nginx service nginx start